### ISSUE TITLE
Examples aren't deleted using 1-click extension

### ISSUE THREAD

**Issue by Coteh** [Jarred-Sumner/1-click-from-github-to-editor#4]
Noticed that unlike the command line version of `git-peek`, which deletes project files after closing the process, the extension doesn't seem to do that at any point. Noticed this this morning when opening up VS Code, noticed the projects I grabbed yesterday using the 1-click are still in my system.

Specs:
Firefox 85.0.1
macOS Catalina 10.15.7

**To Reproduce**
1. Use 1-click tool on Firefox to grab a project (like this one)
2. Copy path generated
3. Close VS Code completely (edit: not sure if this actually does anything, but it's in my steps regardless)
4. Close Firefox completely
5. Access path via `cd` in terminal

**Expected**
It should be deleted

**Actual**
Still there

**Comment by Coteh** [comment]
Can also confirm this issue on Chrome 88.0.4324.150 on macOS

**Comment by Jarred-Sumner** [comment]
This is a bug with the AppleScript launcher, the shell moves the stdin to /dev/null so it has no way of actually knowing when VSCode closes.

It still saves to a temp folder which macOS natively prunes every 3 days. But I agree, this should be better.

**Comment by Jarred-Sumner** [comment]
This is now fixed in Visual Studio Code after you install the latest CLI and re-run `git peek -r`. It is not fixed in other editors yet.
