### ISSUE TITLE
Managed by your organization

### ISSUE THREAD

**Issue by Srini-B** [Jarred-Sumner/1-click-from-github-to-editor#7]
after installing git peek -r on windows, i get the managed tag. It dosen't go even after uninstalling, how do i remove it

![image](https://user-images.githubusercontent.com/22414119/109374971-2fcdf900-78df-11eb-8507-8592671f5654.png)

**Comment by Srini-B** [comment]
found it, no worries

**Comment by Jarred-Sumner** [comment]
Yeah this is unfortunately not something I can fix 

As you can see though, it doesn't really mean much. Its just those policies listed in the JSON.
